<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>04608bb1-cf4f-4594-989e-fd44b0b5fccf</elementGuidId>
    <imagePath></imagePath>
    <name>input_email</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[5]/div[2]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#village</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'village') and equals(@class,'MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1h1jerh')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1h1jerh</value>
        <webElementGuid>f49aa1bf-2cc2-4391-bd42-510c32863ac8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>village</value>
        <webElementGuid>80da87ad-6a21-4ce3-9c9d-3124cfd72e17</webElementGuid>
    </webElementProperties>
</WebElementEntity>