<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>482e3b97-de5f-4d42-8256-6b0c6a9d708b</elementGuidId>
    <imagePath></imagePath>
    <name>input_village</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[5]/div[2]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#email</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'email') and equals(@class,'MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1h1jerh')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1h1jerh</value>
        <webElementGuid>2336864f-a888-4148-8e70-9ffb9352c412</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>email</value>
        <webElementGuid>8e15d49c-d17c-456f-9519-58e782933a28</webElementGuid>
    </webElementProperties>
</WebElementEntity>