<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ae5f3ae5-535f-42ed-9f62-4567c89c8f9a</elementGuidId>
    <imagePath></imagePath>
    <name>input_combo_box_demo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#combo-box-demo</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'combo-box-demo') and equals(@class,'MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd MuiAutocomplete-input MuiAutocomplete-inputFocused css-1563wdh')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd MuiAutocomplete-input MuiAutocomplete-inputFocused css-1563wdh</value>
        <webElementGuid>6374a7fb-cce5-4a24-9a2c-0a5be128e216</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>combo-box-demo</value>
        <webElementGuid>02c124de-202c-4aba-823f-32b0997e727d</webElementGuid>
    </webElementProperties>
</WebElementEntity>