<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ce437bb4-7583-4e18-b95d-e45f9c71393b</elementGuidId>
    <imagePath></imagePath>
    <name>input_contact_switch</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[4]/span[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#contact-switch</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'contact-switch') and equals(@class,'PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3</value>
        <webElementGuid>fc008131-a2c6-4942-8e3c-3d9c8c880685</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>contact-switch</value>
        <webElementGuid>ccf78950-12fc-494d-9bdf-d0ec0c72df70</webElementGuid>
    </webElementProperties>
</WebElementEntity>